### ISSUE TITLE
Tutorial2: wrong code

### ISSUE THREAD

**Issue by mrustl** [modflowpy/flopydoc#1]
In your tutorial 2 on http://modflowpy.github.io/flopydoc/tutorial2.html the following code is wrong: 

`oc = flopy.modflow.ModflowOc(mf, words=words, save_head_every=save_head_every)`
Traceback (most recent call last):

  File "<ipython-input-26-ed91ed7b3830>", line 1, in <module>
    `oc = flopy.modflow.ModflowOc(mf, words=words, save_head_every=save_head_every)`

TypeError: __init__() got an unexpected keyword argument 'save_head_every'

I think it should be corrected according to: 

`stress_period_data = {(0, 0): ['save head',`
                               `'save drawdown',`
                               `'save budget',`
                               `'print head',`
                               `'print budget']}`
`oc = flopy.modflow.ModflowOc(mf, stress_period_data=stress_period_data, compact=True)`

As stated in: https://github.com/modflowpy/flopy/blob/master/examples/Tutorials/Tutorial02/tutorial02.py

**Comment by langevin-usgs** [comment]
Thanks for this.  You are correct.  I've made the changes to the documentation pages.  They will be updated online the next time we rebuild them.
