### ISSUE TITLE
Missing documentation of flopy.mf6.mfsimulation Module

### ISSUE THREAD

**Issue by julian-deltares** [modflowpy/flopydoc#7]
There seems to be some problem with the auto-generated documentation at https://modflowpy.github.io/flopydoc/mfsimulation.html.

It only shows the first doc-string of https://github.com/modflowpy/flopy/blob/develop/flopy/mf6/modflow/mfsimulation.py

**Comment by langevin-usgs** [comment]
Close with https://github.com/modflowpy/flopydoc/commit/53bb98c74a38accaa1db423d798ad59cf1a0c6fa
