### ISSUE TITLE
All links to jupyter notebooks and several other links are dead

### ISSUE THREAD

**Issue by haugwitz** [modflowpy/flopydoc#9]
Hi it seems the dafult URLS for github has changed recently so several links like:
https://github.com/modflowpy/flopy/blob/develop/examples/Notebooks/flopy3_grid_intersection_demo.ipynb

Are now dead.

Is this a temporary github issue or do the links need to be corrected?

**Comment by jlarsen-usgs** [comment]
@haugwitz 

This is a temporary issue that is being worked on right now and will hopefully be fixed soon. Please continue to check back.
